import React from 'react';
import {
  // Heroicons
  HiServer,
  HiShieldCheck,
  HiCodeBracket,
  HiCube,
  HiWifi,
  HiBriefcase,
  HiChartBar,
  HiBeaker,
  HiGlobeAlt,
  HiLightBulb,
  HiAcademicCap,
  HiUserGroup,
  HiDocumentText,
  HiFilm,
  HiCamera,
  HiMicrophone,
  HiChartPie,
  HiShoppingCart,
  HiHome,
  HiBuildingOffice2,
  HiCurrencyDollar,
  HiHeart,
  HiFire,
  HiSparkles,
  HiLockClosed,
  HiEye,
  HiKey,
  HiClipboardCheck,
  HiPuzzlePiece,
  HiCloud,
  HiCog,
  HiCubeTransparent,
  HiLink,
  HiTruck,
  HiPresentationChartLine,
  HiUser,
  HiChatBubbleLeftRight,
  HiComputerDesktop,
  HiDevicePhoneMobile,
  HiCommandLine,
  HiCpuChip,
  HiFingerPrint,
  HiMagnifyingGlass,
  HiShieldExclamation,
  HiBolt,
  HiStar,
  HiRocketLaunch,
  HiPaintBrush,
  HiMusicalNote,
  HiBookOpen,
  HiCalculator,
  HiClock,
  HiCalendar,
  HiFolder,
  HiPaperAirplane,
  HiArrowPath,
  HiArrowRight,
  HiCheckCircle,
  HiXCircle,
  HiInformationCircle,
  HiExclamationTriangle,
  HiQuestionMarkCircle,
  HiTrophy,
} from 'react-icons/hi2';

import {
  // Font Awesome
  FaBrain,
  FaRobot,
  FaDocker,
  FaReact,
  FaNodeJs,
  FaPython,
  FaJava,
  FaEthereum,
  FaShieldAlt,
  FaLock,
  FaCode,
  FaServer,
  FaDatabase,
  FaCloud,
  FaNetworkWired,
  FaChartLine,
  FaBuilding,
  FaBriefcase,
  FaHospital,
  FaUtensils,
  FaShoppingBag,
  FaGamepad,
  FaPalette,
  FaFileAlt,
  FaVideo,
  FaImage,
  FaMicrophoneAlt,
  FaChartBar,
  FaChartPie,
  FaWallet,
  FaTruck,
  FaWarehouse,
  FaIndustry,
  FaLaptopCode,
  FaMobileAlt,
  FaTabletAlt,
  FaDesktop,
  FaLink,
  FaChain,
  FaLockOpen,
  FaEye,
  FaEyeSlash,
  FaKey,
  FaUserSecret,
  FaSearch,
  FaSearchDollar,
  FaPlug,
  FaBug,
  FaExclamationTriangle,
  FaCheckCircle,
  FaTimesCircle,
  FaInfoCircle,
  FaQuestionCircle,
  FaRocket,
  FaStar,
  FaHeart,
  FaFire,
  FaBolt,
  FaMagic,
  FaMusic,
  FaBook,
  FaCalculator,
  FaClock,
  FaCalendarAlt,
  FaFolder,
  FaPaperPlane,
  FaSync,
  FaArrowRight,
  FaComments,
  FaCity,
  FaUsers,
  FaUser,
} from 'react-icons/fa';

import {
  // Simple Icons
  SiKubernetes,
  SiTerraform,
  SiJavascript,
  SiTypescript,
  SiTensorflow,
  SiOpencv,
  SiNumpy,
  SiPandas,
  SiScikitlearn,
  SiBlockchaindotcom,
  SiSolidity,
  SiWeb3DotJs,
  SiNodedotjs,
  SiExpress,
  SiMongodb,
  SiPostgresql,
  SiMysql,
  SiRedis,
  SiDocker,
  SiAmazonaws,
  SiGooglecloud,
  SiMicrosoftazure,
  SiGithubactions,
  SiGitlab,
  SiJenkins,
  SiAnsible,
  SiPuppet,
  SiChef,
  SiVagrant,
  SiPrometheus,
  SiGrafana,
  SiElastic,
  SiKibana,
  SiLogstash,
  SiSplunk,
  SiDatadog,
  SiNewrelic,
  SiSentry,
  SiSonarqube,
  SiCodacy,
  SiCodeclimate,
  SiEslint,
  SiPrettier,
  SiJest,
  SiMocha,
  SiCypress,
  SiSelenium,
  SiPlaywright,
  SiTestinglibrary,
  SiStorybook,
  SiWebpack,
  SiVite,
  SiRollup,
  SiParcel,
  SiBabel,
  SiEslint as SiEslintIcon,
  SiPrettier as SiPrettierIcon,
  SiJest as SiJestIcon,
  SiMocha as SiMochaIcon,
  SiCypress as SiCypressIcon,
  SiSelenium as SiSeleniumIcon,
  SiPlaywright as SiPlaywrightIcon,
  SiTestinglibrary as SiTestingLibraryIcon,
  SiStorybook as SiStorybookIcon,
} from 'react-icons/si';

// Category icon mapping
export const categoryIcons = {
  'ai-ml': HiCpuChip,
  'devops': HiServer,
  'security': HiShieldCheck,
  'frontend': HiCodeBracket,
  'backend': FaDatabase,
  'blockchain': HiCube,
  'iot-sensors': HiWifi,
  'business-apps': HiBriefcase,
  'creative-tools': HiSparkles,
  'entertainment': FaGamepad,
  'external-websites': HiGlobeAlt,
};

// Demo icon mapping based on demo ID or type
export const demoIcons = {
  // AI/ML
  'fraud-detection': FaSearchDollar,
  'deepfake-detection': FaVideo,
  'resume-analyzer': FaFileAlt,
  'ai-assistant': FaRobot,
  'snake-ai': HiSparkles,
  'ai-agents': FaBrain,
  'sentiment-analysis': FaChartLine,
  'ai-language-model': FaBrain,
  'bert-language-model': FaBrain,
  'object-detection': FaEye,
  'audio-transcription': FaMicrophoneAlt,
  'ai-code-generation': FaCode,
  'ml-training-dashboard': FaChartBar,
  'computer-vision-pipeline': FaEye,
  'nlp-sentiment-api': FaChartLine,
  
  // DevOps
  'cicd-pipeline': FaRocket,
  'docker-platform': FaDocker,
  'kubernetes-management': SiKubernetes,
  'terraform-iac': SiTerraform,
  'network-design': FaNetworkWired,
  'academic-network-design': FaNetworkWired,
  
  // Security
  'vulnerability-scanner': FaSearch,
  'penetration-testing': FaUserSecret,
  'encryption-system': FaLock,
  'security-monitoring': HiShieldCheck,
  'waf': HiShieldExclamation,
  'siem': HiChartBar,
  'api-security-gateway': FaKey,
  'phishing-detection': HiMagnifyingGlass,
  'owasp-scanner': FaSearch,
  'network-traffic-analyzer': FaNetworkWired,
  'ids': HiShieldExclamation,
  'threat-intelligence': HiEye,
  
  // External Websites
  'three-sisters-oyster-project': HiCube,
  'bapux-project': HiGlobeAlt,
  'bpawd-project': HiRocketLaunch,
  'uil-academy-project': HiAcademicCap,
  'minbod-project': FaHeart,
  'jf-resume-project': FaFileAlt,
  
  // Blockchain
  'blockchain': FaEthereum,
  'blockchain-advanced': SiBlockchaindotcom,
  
  // Frontend
  'interactive-resume': FaFileAlt,
  'ecommerce': FaShoppingBag,
  
  // Backend
  'rag-chatbot': FaRobot,
  'bookstore-api': FaBook,
  'mern-expense-tracker': FaCalculator,
  'social-network': FaUsers,
  'realtime-chat': HiChatBubbleLeftRight,
  'microservices': HiServer,
  'graphql-api': HiLink,
  'realtime-collaboration-platform': HiUserGroup,
  'event-driven-architecture': HiBolt,
  'serverless-platform': HiCloud,
  'multi-tenant-saas': FaBuilding,
  
  // IoT
  'aquaculture': HiWifi,
  'smart-city': FaCity,
  
  // Business Apps
  'logistics': FaTruck,
  'healthcare': FaHospital,
  'financial': FaChartLine,
  'restaurant-app': FaUtensils,
  'saas-analytics': FaChartPie,
  'advanced-analytics': FaChartBar,
  'real-time-collaboration': FaUsers,
  'ai-interview-simulator': FaUser,
  'edge-computing': HiCloud,
  'quantum-computing': HiSparkles,
  'daily-planner': FaCalendarAlt,
  
  // Creative Tools
  'whiteboard': HiPaintBrush,
  'portfolio-builder': HiBriefcase,
  'product-configurator': HiPuzzlePiece,
  
  // Entertainment
  'game-platform': FaGamepad,
  
  // Additional mappings for missing demos
  'cicd-pipeline': FaRocket,
  'docker-platform': FaDocker,
  'kubernetes-management': SiKubernetes,
  'terraform-iac': SiTerraform,
  'network-design': FaNetworkWired,
  'academic-network-design': FaNetworkWired,
  'vulnerability-scanner': FaSearch,
  'penetration-testing': FaUserSecret,
  'encryption-system': FaLock,
  'security-monitoring': HiShieldCheck,
  'java': FaJava,
  'python': FaPython,
  'education': HiAcademicCap,
  'sports': HiTrophy,
};

// Default icon for unmapped items
export const DefaultIcon = HiCube;

// Helper function to get icon component
export const getIcon = (iconKey, type = 'demo') => {
  if (!iconKey) {
    return DefaultIcon;
  }
  if (type === 'category') {
    return categoryIcons[iconKey] || DefaultIcon;
  }
  return demoIcons[iconKey] || DefaultIcon;
};

// Helper component to render icon
export const Icon = ({ iconKey, type = 'demo', className = '', size = 24, ...props }) => {
  const IconComponent = getIcon(iconKey, type);
  return <IconComponent className={className} size={size} {...props} />;
};

export default Icon;
